module.exports = {
  users: require("./users"),
  staffs: require("./staffs"),
  invoice: require("./invoice"),
  receipt: require("./receipts"),
  purchase: require("./purchase"),
  payment: require("./payment"),
  config: require("./config"),
  collection: require("./collection"),
  whitelabel: require("./whitelabel"),
  order: require("./order"),
  quote: require("./quote"),
  role: require("./role"),
  employee: require("./employee"),
  store: require("./store"),
  adSchema: require("./adSchema"),
  subPlan: require("./subPlan"),
  faqDocument: require("./faqDocument"),
  chat: require("./chat"),
  dynamicPage: require("./dynamicPage"),
};
