import adminRoutes from "./admin.routes.js";
import businessRoutes from "./business.routes.js";
import staffsRoutes from "./staffs.routes.js";
import invoiceRoutes from "./invoice.routes.js";
import purchaseRoutes from "./purchase.routes.js";
import receiptRoutes from "./receipt.routes.js";
import configRoutes from "./config.routes.js";
import paymentRoutes from "./payment.routes.js";
import collectionRoutes from "./collection.routes.js";
import dynamicRoutes from "./dynamic.routes.js";
import adminCollectionRoutes from "./adminCollection.routes.js";
import adminDynamicRoutes from "./adminDynamic.routes.js";
import whiteLabelRoutes from "./whiteLabel.routes.js";
import orderRoutes from "./order.routes.js";
import quoteRoutes from "./quote.routes.js";
import roleRoutes from "./role.routes.js";
import employeesRoutes from "./employees.routes.js";
import storeRoutes from "./store.routes.js";
import adSchemaRoutes from "./adSchema.routes.js";
import subPlanRoutes from "./subPlan.routes.js";
import chatRoutes from "./chat.routes.js";
import faqDocsRoutes from "./faqDocs.routes.js";
import dynamicPageRoutes from "./dynamicPage.routes.js";
import chatbotRoutes from "./chatbot.routes.js";
import reportRoutes from "./report.routes.js";

export default function (app) {
  adminRoutes(app);
  businessRoutes(app);
  staffsRoutes(app);
  invoiceRoutes(app);
  purchaseRoutes(app);
  receiptRoutes(app);
  configRoutes(app);
  paymentRoutes(app);
  collectionRoutes(app);
  dynamicRoutes(app);
  adminCollectionRoutes(app);
  adminDynamicRoutes(app);
  whiteLabelRoutes(app);
  orderRoutes(app);
  quoteRoutes(app);
  roleRoutes(app);
  employeesRoutes(app);
  storeRoutes(app);
  adSchemaRoutes(app);
  subPlanRoutes(app);
  chatRoutes(app);
  faqDocsRoutes(app);
  dynamicPageRoutes(app);
  chatbotRoutes(app);
  reportRoutes(app);
}
